version: '2'
services:
  eurekaserver:
    image: antoniadis/eurekasvr:version1
    ports:
       - "8761:8761"
  configserver:
      image: antoniadis/confsvr:version1
      ports:
        - "8888:8888"
      environment:
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        EUREKASERVER_PORT: "8761"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  graphqlservice:
    image: antoniadis/graphql-server:version1
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "IMSYMMETRIC"