#
#   This is the core configuration for a configuration service.
#   A configuration service that uses a git-based repository to read the files from
#
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/bantoniadis/config-repo/
          searchPaths: graphqlservice,zuulservice
#          username: native-cloud-apps
#          password: 0ffended